kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rpi-gd-storage-class
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /rpi-gd/data
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpi-gd-pvc
spec:
  storageClassName: rpi-gd-storage-class
  accessModes: [ReadWriteOnce]
  resources: {requests: {storage: 1Mi}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carport-opcua-plc-deployment
spec:
  selector:
    matchLabels:
      app: carport-opcua-server
  template:
    metadata:
      labels:
        app: carport-opcua-server
    spec:
      volumes:
      - name: rpi-gd-volume
        persistentVolumeClaim:
          claimName: rpi-gd-pvc
      containers:
      - name: carport-opcua-server
        image: iotccrscotts.azurecr.io/carport-opcua-plc:1.0.0-arm64v8
        ports:
        - containerPort: 4334
        volumeMounts:
        - name: rpi-gd-volume
          mountPath: /rpi-gd/data
        securityContext:
          privileged: true
      imagePullSecrets:
      - name: rpi-gd-acr-access
---
apiVersion: v1
kind: Service
metadata:
  name: carport-opcua-plc-service
spec:
  type: LoadBalancer
  selector:
    app: carport-opcua-server
  ports:
  - name: carport-opcua-server
    protocol: TCP
    port: 4334
    targetPort: 4334
